import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "./Providers";
import "./globals.css";
import Navbar from "./components/Navbar";
import { useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });
console.log("🚀 ~ inter:", inter)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
